language: node_js
node_js:
  - node
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run test:cover
after_success:
  - npm run coverage
  - npm run semantic-release

